// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: proto/snapshot.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TypeState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Min float64 `protobuf:"fixed64,1,opt,name=min,proto3" json:"min,omitempty"`
	Max float64 `protobuf:"fixed64,2,opt,name=max,proto3" json:"max,omitempty"`
	Val float64 `protobuf:"fixed64,3,opt,name=val,proto3" json:"val,omitempty"`
	Gen *Curve  `protobuf:"bytes,4,opt,name=gen,proto3" json:"gen,omitempty"`
}

func (x *TypeState) Reset() {
	*x = TypeState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_snapshot_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TypeState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeState) ProtoMessage() {}

func (x *TypeState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_snapshot_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeState.ProtoReflect.Descriptor instead.
func (*TypeState) Descriptor() ([]byte, []int) {
	return file_proto_snapshot_proto_rawDescGZIP(), []int{0}
}

func (x *TypeState) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *TypeState) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *TypeState) GetVal() float64 {
	if x != nil {
		return x.Val
	}
	return 0
}

func (x *TypeState) GetGen() *Curve {
	if x != nil {
		return x.Gen
	}
	return nil
}

type SensorState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Min  float64 `protobuf:"fixed64,1,opt,name=min,proto3" json:"min,omitempty"`
	Max  float64 `protobuf:"fixed64,2,opt,name=max,proto3" json:"max,omitempty"`
	ValX float64 `protobuf:"fixed64,3,opt,name=val_x,json=valX,proto3" json:"val_x,omitempty"`
	ValY float64 `protobuf:"fixed64,4,opt,name=val_y,json=valY,proto3" json:"val_y,omitempty"`
	Name string  `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Gen  *Curve  `protobuf:"bytes,6,opt,name=gen,proto3" json:"gen,omitempty"`
}

func (x *SensorState) Reset() {
	*x = SensorState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_snapshot_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SensorState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorState) ProtoMessage() {}

func (x *SensorState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_snapshot_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorState.ProtoReflect.Descriptor instead.
func (*SensorState) Descriptor() ([]byte, []int) {
	return file_proto_snapshot_proto_rawDescGZIP(), []int{1}
}

func (x *SensorState) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *SensorState) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *SensorState) GetValX() float64 {
	if x != nil {
		return x.ValX
	}
	return 0
}

func (x *SensorState) GetValY() float64 {
	if x != nil {
		return x.ValY
	}
	return 0
}

func (x *SensorState) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SensorState) GetGen() *Curve {
	if x != nil {
		return x.Gen
	}
	return nil
}

type Curve struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Points []*Curve_ControlPoint `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	Mode   int64                 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
}

func (x *Curve) Reset() {
	*x = Curve{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_snapshot_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Curve) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Curve) ProtoMessage() {}

func (x *Curve) ProtoReflect() protoreflect.Message {
	mi := &file_proto_snapshot_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Curve.ProtoReflect.Descriptor instead.
func (*Curve) Descriptor() ([]byte, []int) {
	return file_proto_snapshot_proto_rawDescGZIP(), []int{2}
}

func (x *Curve) GetPoints() []*Curve_ControlPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

func (x *Curve) GetMode() int64 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type Curve_Point struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float64 `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float64 `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Curve_Point) Reset() {
	*x = Curve_Point{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_snapshot_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Curve_Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Curve_Point) ProtoMessage() {}

func (x *Curve_Point) ProtoReflect() protoreflect.Message {
	mi := &file_proto_snapshot_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Curve_Point.ProtoReflect.Descriptor instead.
func (*Curve_Point) Descriptor() ([]byte, []int) {
	return file_proto_snapshot_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Curve_Point) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Curve_Point) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Curve_ControlPoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vp *Curve_Point `protobuf:"bytes,1,opt,name=vp,proto3" json:"vp,omitempty"`
	Cp *Curve_Point `protobuf:"bytes,2,opt,name=cp,proto3" json:"cp,omitempty"`
}

func (x *Curve_ControlPoint) Reset() {
	*x = Curve_ControlPoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_snapshot_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Curve_ControlPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Curve_ControlPoint) ProtoMessage() {}

func (x *Curve_ControlPoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_snapshot_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Curve_ControlPoint.ProtoReflect.Descriptor instead.
func (*Curve_ControlPoint) Descriptor() ([]byte, []int) {
	return file_proto_snapshot_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Curve_ControlPoint) GetVp() *Curve_Point {
	if x != nil {
		return x.Vp
	}
	return nil
}

func (x *Curve_ControlPoint) GetCp() *Curve_Point {
	if x != nil {
		return x.Cp
	}
	return nil
}

var File_proto_snapshot_proto protoreflect.FileDescriptor

var file_proto_snapshot_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x61, 0x0a,
	0x09, 0x54, 0x79, 0x70, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6d, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x61, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x12, 0x10,
	0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x76, 0x61, 0x6c,
	0x12, 0x1e, 0x0a, 0x03, 0x67, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x75, 0x72, 0x76, 0x65, 0x52, 0x03, 0x67, 0x65, 0x6e,
	0x22, 0x8f, 0x01, 0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6d,
	0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x03, 0x6d, 0x61, 0x78, 0x12, 0x13, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x5f, 0x78, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x04, 0x76, 0x61, 0x6c, 0x58, 0x12, 0x13, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x5f, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x76, 0x61, 0x6c, 0x59, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x03, 0x67, 0x65, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x75, 0x72, 0x76, 0x65, 0x52, 0x03, 0x67,
	0x65, 0x6e, 0x22, 0xcb, 0x01, 0x0a, 0x05, 0x43, 0x75, 0x72, 0x76, 0x65, 0x12, 0x31, 0x0a, 0x06,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x75, 0x72, 0x76, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x6d,
	0x6f, 0x64, 0x65, 0x1a, 0x23, 0x0a, 0x05, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x0c, 0x0a, 0x01,
	0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x79, 0x1a, 0x56, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x74,
	0x72, 0x6f, 0x6c, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x22, 0x0a, 0x02, 0x76, 0x70, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x75, 0x72,
	0x76, 0x65, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x02, 0x76, 0x70, 0x12, 0x22, 0x0a, 0x02,
	0x63, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x43, 0x75, 0x72, 0x76, 0x65, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x02, 0x63, 0x70,
	0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_snapshot_proto_rawDescOnce sync.Once
	file_proto_snapshot_proto_rawDescData = file_proto_snapshot_proto_rawDesc
)

func file_proto_snapshot_proto_rawDescGZIP() []byte {
	file_proto_snapshot_proto_rawDescOnce.Do(func() {
		file_proto_snapshot_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_snapshot_proto_rawDescData)
	})
	return file_proto_snapshot_proto_rawDescData
}

var file_proto_snapshot_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_snapshot_proto_goTypes = []interface{}{
	(*TypeState)(nil),          // 0: proto.TypeState
	(*SensorState)(nil),        // 1: proto.SensorState
	(*Curve)(nil),              // 2: proto.Curve
	(*Curve_Point)(nil),        // 3: proto.Curve.Point
	(*Curve_ControlPoint)(nil), // 4: proto.Curve.ControlPoint
}
var file_proto_snapshot_proto_depIdxs = []int32{
	2, // 0: proto.TypeState.gen:type_name -> proto.Curve
	2, // 1: proto.SensorState.gen:type_name -> proto.Curve
	4, // 2: proto.Curve.points:type_name -> proto.Curve.ControlPoint
	3, // 3: proto.Curve.ControlPoint.vp:type_name -> proto.Curve.Point
	3, // 4: proto.Curve.ControlPoint.cp:type_name -> proto.Curve.Point
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_snapshot_proto_init() }
func file_proto_snapshot_proto_init() {
	if File_proto_snapshot_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_snapshot_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TypeState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_snapshot_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SensorState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_snapshot_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Curve); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_snapshot_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Curve_Point); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_snapshot_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Curve_ControlPoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_snapshot_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_snapshot_proto_goTypes,
		DependencyIndexes: file_proto_snapshot_proto_depIdxs,
		MessageInfos:      file_proto_snapshot_proto_msgTypes,
	}.Build()
	File_proto_snapshot_proto = out.File
	file_proto_snapshot_proto_rawDesc = nil
	file_proto_snapshot_proto_goTypes = nil
	file_proto_snapshot_proto_depIdxs = nil
}
